meta_product_name: "Harvest Sharing"
meta_title: "Harvest Sharing - LA NATURE NOUS RASSEMBLE"
meta_description: "Pour les autres:
Pour permettre à d'autres personnes d'avoir accès à de bons fruits et légumes
qui ont poussé le plus naturellement possible près de chez elles.
Pour démocratiser l'accès à certains produits devenus chers alors qu'ils
pourrissent dans les jardins.
Pour refaire découvrir des saveurs qui se sont perdues.
Et pour vous aussi :
Pour faire de belles rencontres avec des personnes sensibles aux mêmes valeurs que vous.
Pour vous permettre de couvrir le coût de vos graines/semences de bonne qualité."
meta_image: "cover.png" # should exist in `app/assets/images/`
